### ISSUE TITLE
Bot mention loop

### ISSUE THREAD

**Issue by umm-maybe** [zacc/ssi-bot#41]
The default reply probability calculation in logic_mixin.py forces bots to reply to any mention of their username, regardless of comment level in thread.  In combination with GPT-2's tendency to mimic input text, this can lead to a cavalcade of bots mentioning other bots, essentially overflowing a thread with comments and precluding all other activity on the sub.  One way to deal with this is to have the reply probability when responding to mentions start at 1 but then be subject to the same thread level restrictions and decay weighting as other comments; in the longer term a rate limiter or cap on total comments per unit time might be effective solutions as well.

**Comment by zacc** [comment]
We modified it in b4a56e1744ef76982939dcd7a1fc5434427fd61c for mention replies to be subject to normal time decay.
