### ISSUE TITLE
Possible to switch from google colab to kaggle?

### ISSUE THREAD

**Issue by Not-AriStienfeld** [zacc/ssi-bot#46]
Kaggle would allow guaranteed 30 hours of a t4 accelerator per week, which is probably enough to train a basic bot. Kaggle also doesn't have anti-afk features. also once you use up your t4 time you have 40 hours of k80 time.

**Comment by zacc** [comment]
It's a good idea.
@Not-AriStienfeld  and I discussed a possible limitation with disk space on kaggle.

A good first step will be to take the current colab script and put it as a file in this repo. Then people can import it into whichever tool they want more easily and we can also track changes to the script.

**Comment by zacc** [comment]
Put the ipynb into the repo so it can be versioned properly.
I have also updated the instructions.
https://github.com/zacc/ssi-bot/commit/877607d7000b1a7dcfdb0c07d8a8394f1aad8768
