### ISSUE TITLE
Abandon on negative keyword 

### ISSUE THREAD

**Issue by AJStangl** [zacc/ssi-bot#61]
> the other thing in multibot is that if there was a negative keyword, it will just regenerate a new one. in the old system, it there was a negative keyword it would just abandon that reply. so we might have picked up a lot of new replies via that, too and that needs to be compensated by dialing down the reply frequency further

**Comment by zacc** [comment]
Attempt to address this here: https://github.com/zacc/ssi-bot/commit/d437943b8ba3005010391c58e0c0c783f2333a25
